apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-backend-app       
  labels:
    app: secure-java-api
spec:
  replicas: 1                     
  selector:
    matchLabels:
      app: secure-java-api        
  template:
    metadata:
      labels:
        app: secure-java-api      
    spec:
      containers:
      - name: spring-boot-container
        image: ghcr.io/tu-usuario/secure-fintech-backend:latest 
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080    
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials 
              key: password        